### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by ProfFan** [katyo/esp-partition-table#1]
```
    // Read the partition table
    let partition_table = ept::PartitionTable::default();
    let mut storage = FlashStorage::new();
    for partition in partition_table.iter_storage(&mut storage, false) {
        let partition = partition.unwrap();
        defmt::info!("Partition: {:?}, offset: {:#x}", partition.name(), partition.offset);
    }
```

**Comment by katyo** [comment]
@ProfFan Could you make pull request?

**Comment by thomas725** [comment]
Please explain the `FlashStorage::new();` - So far I could only find `RmwNorFlashStorage::new(...)`  & `RmwMultiwriteNorFlashStorage::new(...)` in `embedded-storage` v.0.3.1 and both need parameters I don't understand how to provide.

**Comment by TheTechRobo** [comment]
You want `FlashStorage` from `esp-storage`, which implements the `embedded-storage` traits for the ESP32.

**Comment by thomas725** [comment]
Thank you, equipped with that knowledge I managed to make it work! 🎉 

Cargo.toml:
```toml
# https://docs.rs/crate/esp-storage/0.5.0
[profile.dev.package.esp-storage]
opt-level = 3
[profile.release.package.esp-storage]
opt-level = 3

[dependencies]
# need "embedded-storage" feature to get `iter_storage` function
esp-partition-table = { version = "=0.1.3", default-features = false, features = ["embedded-storage"]}
esp-storage = { version = "=0.5.0", features = ["esp32"] }
```

\+ rust code nearly identical to that posted by ProfFan 1,5 years ago 😃
